# Generated by Django 2.1.7 on 2019-03-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user that this Stripe event is related to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipper',
            name='store',
            field=models.ForeignKey(help_text='The store this shipper belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='shippers', to='ecommerce.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(help_text='The store this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.Store'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The user whom this purchase order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='The product that will be ordered for this order item.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user whom created this purchase order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user whom last modified this purchase order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, help_text='The shipper whom is responsible for delivering this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce.Shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(help_text='The store this order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='The user whom this purchase order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
