# Generated by Django 2.1.7 on 2019-03-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='payment_plan_id',
            field=models.CharField(blank=True, help_text='The plan ID set by the payment merchant.', max_length=127, null=True, verbose_name='Payment Plan ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='payment_product_id',
            field=models.CharField(blank=True, help_text='The product ID set by the payment merchant.', max_length=127, null=True, verbose_name='Payment Product ID'),
        ),
    ]
