from device.serializers.device_crud_api_serializers import DeviceListCreateSerializer
from device.serializers.device_crud_api_serializers import DeviceRetrieveUpdateDestroySerializer
from device.serializers.device_crud_api_serializers import DeviceProfileSerializer
