from device.serializers.device_crud_api_serializers import DeviceListCreateSerializer
from device.serializers.device_crud_api_serializers import DeviceRetrieveUpdateDestroySerializer
from device.serializers.device_crud_api_serializers import DeviceProfileSerializer
from device.serializers.device_operation_api_serializers import DeviceActivateOperationSerializer
from device.serializers.device_operation_api_serializers import DeviceInstrumentSetTimeSeriesDatumeOperationSerializer

from device.serializers.tsd_crud_serializers import TimeSeriesDatumCreateSerializer
from device.serializers.tsd_crud_serializers import TimeSeriesDataListSerializer
