# from task.views.gui_views.instrument_task_email_view import InstrumentTaskEmailWebBrowserView
# from task.views.gui_views.production_task_email_view import ProductionTaskEmailWebBrowserView
from task.views.resource_views.task_item_list_view import TaskItemsListAPIView
from task.views.resource_views.task_item_retrieve_view import TaskItemRetrieveAPIView
# from task.views.resource_views.task_item_was_viewed_func_view import TaskItemWasViewedFuncAPIView
