# Generated by Django 2.1.7 on 2019-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_percent',
            field=models.FloatField(default=1, help_text='The tax percent that was for calculating this invoices tax.', verbose_name='Tax Percent'),
            preserve_default=False,
        ),
    ]
