# Generated by Django 2.2.1 on 2019-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentsimulator',
            name='is_running',
            field=models.BooleanField(blank=True, default=True, help_text='Controls whether the simulator is running or not.', verbose_name='Is Running'),
        ),
    ]
