# Generated by Django 2.2.1 on 2019-05-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncropinspection',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Production Crop Inspection', 'verbose_name_plural': 'Production Crop Inspections'},
        ),
    ]
