# Generated by Django 2.2.1 on 2019-05-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_measured_unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_measured_value',
        ),
    ]
