# Generated by Django 2.1.7 on 2019-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentsimulator',
            name='is_running',
            field=models.BooleanField(blank=True, default=False, help_text='Controls whether the simulator is running or not.', verbose_name='Is Running'),
        ),
    ]
