# Generated by Django 2.2.1 on 2019-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncrop',
            name='current_stage',
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Plant'), (2, 'Fishstock'), (3, 'Animalstock'), (0, 'None')], default=1, help_text='The type of production crop.', verbose_name='Type of'),
            preserve_default=False,
        ),
    ]
