# Generated by Django 2.2.1 on 2019-05-21 21:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncrop',
            name='evaluation_dict',
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='evaluation_failures',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The evaluation conditions which failed for this production crop.', max_length=511, null=True, verbose_name='Evaluation Failure(s)'),
        ),
    ]
