# Generated by Django 2.1.7 on 2019-03-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_product_id',
            field=models.CharField(blank=True, help_text='The product ID set by the payment merchant.', max_length=127, null=True, verbose_name='Payment Product ID'),
        ),
    ]
