# Generated by Django 2.2.1 on 2019-07-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Coming Soon'), (3, 'Publised')], default=1, help_text='The state of product.', verbose_name='State'),
        ),
    ]
