# Generated by Django 2.2.1 on 2019-05-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncrop',
            name='crop',
            field=models.ForeignKey(default=1, help_text='The plants or fish that we are growing in production.', on_delete=django.db.models.deletion.CASCADE, related_name='production_crops', to='foundation.Crop', verbose_name='Crop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productioncrop',
            name='production',
            field=models.ForeignKey(help_text='The production this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='foundation.Production', verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='productioncropinspection',
            name='production_crop',
            field=models.ForeignKey(help_text='The plants or fish that we are evaluating for this quality assurance inspection.', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='foundation.ProductionCrop', verbose_name='Production Crop'),
        ),
    ]
