# Generated by Django 2.1.7 on 2019-04-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Purchase Pending'), (3, 'Purchase Failed'), (4, 'Purchased'), (5, 'Building'), (6, 'Shipping / On route'), (7, 'Delivered'), (0, 'Error')], default=1, help_text='The state of the invoice.', verbose_name='State'),
        ),
    ]
