# Generated by Django 2.1.7 on 2019-03-13 23:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_status',
        ),
        migrations.AddField(
            model_name='user',
            name='customer_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The customer details from the payment merchant.', null=True, verbose_name='Customer Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, help_text='The customer ID from the payment merchant.', max_length=127, null=True, verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('not_interested', 'Not Interested'), ('tracking', 'Trailing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='not_interested', help_text='The customer subscription status from the payment merchant.', max_length=15, verbose_name='Subscription Status'),
        ),
    ]
