# Generated by Django 2.1.7 on 2019-04-17 04:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, help_text='A longitude and latitude coordinates of this device. For example -81.245277,42.984924 (<a href="https://en.wikipedia.org/wiki/World_Geodetic_System">WGS 84</a>).', null=True, srid=4326, verbose_name='Location'),
        ),
    ]
