# Generated by Django 2.1.7 on 2019-04-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='The date/time that the customer received their order for this invoice.', null=True, verbose_name='Delivered at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchased_at',
            field=models.DateTimeField(blank=True, help_text='The date/time that the customer purchased this invoice.', null=True, verbose_name='Purchased at'),
        ),
    ]
