# Generated by Django 2.1.7 on 2019-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_shipping_same_as_billing',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicates whether the shipping information is the same as the billing information.', verbose_name='Is shipping information same as billing information'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_given_name',
            field=models.CharField(blank=True, help_text='The given name used for billing.', max_length=127, null=True, verbose_name='Billing Given Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_last_name',
            field=models.CharField(blank=True, help_text='The last name used for billing.', max_length=127, null=True, verbose_name='Billing Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shipping_same_as_billing',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicates whether the shipping information is the same as the billing information.', verbose_name='Is shipping information same as billing information'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_given_name',
            field=models.CharField(blank=True, help_text='The given name used for shipping.', max_length=127, null=True, verbose_name='Shipping Given Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_last_name',
            field=models.CharField(blank=True, help_text='The last name used for shipping.', max_length=127, null=True, verbose_name='Shipping Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='The email used for billing', max_length=255, null=True, verbose_name='Billing Email'),
        ),
    ]
