# Generated by Django 2.2.1 on 2019-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, help_text='Is this device verified by Mikaponics. Only devices built by Mikaponics can be verified.', verbose_name='Is verified'),
        ),
    ]
