# Generated by Django 2.1.7 on 2019-03-25 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='last_recorded_datum',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='statistics',
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_max_timestamp_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The datetime of the last 24h measured maximum value since operation.', null=True, verbose_name='Last 24h maximum datetime'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_max_value',
            field=models.FloatField(blank=True, editable=False, help_text='The lastest measured maximum value within the last 24 hours of operation.', null=True, verbose_name='Last 24h maximum value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_mean_value',
            field=models.FloatField(blank=True, editable=False, help_text='The latest measured mean value within the last 24 hours of operation.', null=True, verbose_name='Last 24h mean value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_median_value',
            field=models.FloatField(blank=True, editable=False, help_text='The value of the datum.', null=True, verbose_name='last_24h_median_value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_min_timestamp_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The datetime of the last 24h measured minimum value since operation.', null=True, verbose_name='Last 24h minimum datetime'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_min_value',
            field=models.FloatField(blank=True, editable=False, help_text='The lastest measured minimum value within the last 24 hours of operation.', null=True, verbose_name='Last 24h minimum value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_mode_value',
            field=models.FloatField(blank=True, editable=False, help_text='The latest measured mode value within the last 24 hours of operation.', null=True, verbose_name='Last 24h mode value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_mode_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='The latest measured mode values within the last 24 hours of operation.', null=True, verbose_name='last 24h mode values'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_range_value',
            field=models.FloatField(blank=True, editable=False, help_text='The latest measured range value within the last 24 hours of operation.', null=True, verbose_name='Last 24h range value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_stedv_value',
            field=models.FloatField(blank=True, editable=False, help_text='The value of the datum.', null=True, verbose_name='last_24h_stedv_value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_24h_variance_value',
            field=models.FloatField(blank=True, editable=False, help_text='The value of the datum.', null=True, verbose_name='last_24h_variance_value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_measured_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The datetime of the last measured value since operation.', null=True, verbose_name='Last measured at'),
        ),
    ]
