# Generated by Django 2.1.7 on 2019-05-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='The coupon used by this coupon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='foundation.Coupon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default='icUg5pcX5ND8zQgpspLFEA6dGfzKNk7', help_text='The referral code which can be given out to other users.', max_length=31, null=True, unique=True, verbose_name='Referral Code'),
        ),
    ]
