# Generated by Django 2.2.1 on 2019-05-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninspection',
            name='task_item',
            field=models.ForeignKey(blank=True, help_text='The task item this inspection belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foundation.TaskItem', verbose_name='Task Item'),
        ),
    ]
