# Generated by Django 2.2.1 on 2019-05-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='alertitem',
            index_together={('user', 'type_of', 'state', 'created_at')},
        ),
    ]
