# Generated by Django 2.2.1 on 2019-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190514_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncropinspection',
            name='review',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Bad'), (3, 'Average'), (2, 'Good'), (1, 'Excellent')], help_text='The review of the user for this crop at this time.', null=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='productioncropinspection',
            name='stage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The observed stage in the life cycle by the user.', null=True, verbose_name='Life Cycle Stage'),
        ),
    ]
