# Generated by Django 2.1.7 on 2019-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190325_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_recorded_datum',
        ),
        migrations.RemoveField(
            model_name='device',
            name='statistics',
        ),
        migrations.AddField(
            model_name='device',
            name='last_measured_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The datetime of the last measured value since operation.', null=True, verbose_name='Last measured at'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_measured_unit_of_measure',
            field=models.FloatField(blank=True, editable=False, help_text='The last measured unit of measure since operation.', null=True, verbose_name='Last measured unit of measure'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_measured_value',
            field=models.FloatField(blank=True, editable=False, help_text='The last measured value since operation.', null=True, verbose_name='Last measured value'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_measured_value',
            field=models.FloatField(blank=True, editable=False, help_text='The last measured value since operation.', null=True, verbose_name='Last measured value'),
        ),
    ]
