# Generated by Django 2.2.1 on 2019-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190508_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropsubstrate',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Plant'), (2, 'Fishstock'), (3, 'Animalstock'), (0, 'None')], default=1, help_text='The type of crop being grown in production.', verbose_name='Type of'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='grow_system',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Wick System'), (3, 'Deep Water Culture System'), (4, 'Ebb & Flow System'), (5, 'Nutrient Film Technique System'), (6, 'Drip System'), (7, 'Aeroponic System'), (8, 'Vertical Tower System'), (1, 'Other (Please specify)')], help_text='The growth system being used for crop production.', verbose_name='Grow System'),
        ),
    ]
