# Generated by Django 2.2.1 on 2019-07-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190706_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='was_success_at_finish',
            new_name='was_success',
        ),
    ]
