# Generated by Django 2.2.1 on 2019-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_productioncrop_average_measure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncrop',
            name='variety',
            field=models.CharField(blank=True, help_text='The variety name of the crop.', max_length=127, null=True, verbose_name='Variety'),
        ),
    ]
