# Generated by Django 2.2.1 on 2019-05-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_productioninspection_task_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioninspection',
            name='task_item',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='production',
            field=models.OneToOneField(blank=True, help_text='The production this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_item', to='foundation.Production'),
        ),
    ]
