# Generated by Django 2.2.1 on 2019-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190703_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default=1, help_text='The icon for this product.', max_length=31, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='The sort number of product.', verbose_name='Sort #'),
        ),
    ]
