# Generated by Django 2.2.1 on 2019-07-09 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190709_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Coming Soon'), (4, 'Hidden'), (3, 'Publised')], default=1, help_text='The state of product.', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The unique identifier used by us to identify our OAuth application.', unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='The unique slug used for this application when accessing details page.', max_length=127, unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='The name of this application.', max_length=63, verbose_name='Name')),
                ('description', models.TextField(help_text='A a description of this application.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_applications', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_user_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user whom this application belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Application',
                'verbose_name_plural': 'User Applications',
                'db_table': 'mika_user_applications',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
