# Generated by Django 2.1.7 on 2019-04-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190417_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='An alias for the device.', max_length=255, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(default='', help_text='A description of the device.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='The name of the device.', max_length=255, verbose_name='Name'),
        ),
    ]
