# Generated by Django 2.2.1 on 2019-07-04 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190704_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='time_step',
            field=models.DurationField(choices=[(datetime.timedelta(0, 60), 'Every minute'), (datetime.timedelta(0, 300), 'Every 5 minutes'), (datetime.timedelta(0, 900), 'Every 15 minutes'), (datetime.timedelta(0, 1800), 'Every 30 minutes'), (datetime.timedelta(0, 3600), 'Every hour')], default=datetime.timedelta(0, 60), help_text='The time difference between the previous time series datum to the new time-series datum. This is the interval which will be used for all time-series data generated.', verbose_name='Time Step'),
        ),
    ]
