# Generated by Django 2.2.1 on 2019-05-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190517_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncrop',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Production Crop', 'verbose_name_plural': 'Production Crops'},
        ),
    ]
