# Generated by Django 2.2.1 on 2019-05-21 21:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190521_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncrop',
            name='evaluation_passes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The dictionary of instrument slugs which passed the evaluation.', max_length=127, null=True, verbose_name='Evaluation Pass(es)'),
        ),
        migrations.AlterField(
            model_name='productioncrop',
            name='evaluation_failures',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The dictionary of instrument slugs and the condition failed for the instrument in the computed evaluation.', max_length=255, null=True, verbose_name='Evaluation Failure(s)'),
        ),
    ]
