# Generated by Django 2.1.7 on 2019-03-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20190313_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', help_text='The timezone the user belongs to.', max_length=63, verbose_name='Timezone'),
        ),
    ]
