# Generated by Django 2.2.1 on 2019-05-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_production_productioninspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the crop.', max_length=31, unique=True, verbose_name='Name')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'Plant'), (3, 'Fishstock')], help_text='The type of crop being grown in production.', verbose_name='Type of')),
                ('order_number', models.PositiveSmallIntegerField(help_text='The order number to list this crop in.', verbose_name='Order #')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crop',
                'db_table': 'mika_crops',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CropSubstrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the crop substrate.', max_length=31, unique=True, verbose_name='Name')),
                ('order_number', models.PositiveSmallIntegerField(help_text='The order number to list this crop substrate by.', verbose_name='Order #')),
            ],
            options={
                'verbose_name': 'Crop Substrate',
                'verbose_name_plural': 'Crop Substrates',
                'db_table': 'mika_crop_substrates',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionCrop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='The unique slug used for this crop when accessing details page.', max_length=127, unique=True, verbose_name='Slug')),
                ('crop_other', models.CharField(blank=True, help_text='The name of crop the user is producing in production that is not in our system.', max_length=255, null=True, verbose_name='Crop (Other)')),
                ('quantity', models.PositiveSmallIntegerField(help_text='The quantity of plants or fish that are being produced.', verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address of the creator.', null=True, verbose_name='Created from IP')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, editable=False, help_text='Is creator a public IP and is routable.', verbose_name='Is created from IP public?')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from IP')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, editable=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is Last modified from IP public?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user whom created this food production inspections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_crops', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, help_text='The plants or fish that we are growing in production.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_crops', to='foundation.Crop', verbose_name='Crop')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The user whom last modified this food production inspection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_production_crops', to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(blank=True, help_text='The production this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='foundation.Production', verbose_name='Production')),
            ],
            options={
                'verbose_name': 'Production Inspection',
                'verbose_name_plural': 'Production Inspections',
                'db_table': 'mika_production_crops',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='ProductionInspection',
        ),
    ]
