# Generated by Django 2.2.1 on 2019-07-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190706_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncrop',
            name='harvest_at_finish',
        ),
        migrations.RemoveField(
            model_name='productioncrop',
            name='harvest_failure_reason_at_finish',
        ),
        migrations.RemoveField(
            model_name='productioncrop',
            name='state_at_finish',
        ),
        migrations.RemoveField(
            model_name='productioncrop',
            name='state_failure_reason_at_finish',
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='average_height',
            field=models.FloatField(blank=True, help_text='The average height of the production crop at completion.', null=True, verbose_name='Average Height'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='average_length',
            field=models.FloatField(blank=True, help_text='The average length of the production crop at completion.', null=True, verbose_name='Average Length'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='average_width',
            field=models.FloatField(blank=True, help_text='The average wdith of the production crop at completion.', null=True, verbose_name='Average Width'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_failure_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Pest Problem'), (3, 'Disease Problem'), (4, 'Abiotic Problem'), (5, 'Technical Problem'), (6, 'Human Error'), (1, 'Other')], help_text='The reason why this crop production was not harvested.', null=True, verbose_name='Harvest Failure Reason'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_failure_reason_other',
            field=models.CharField(blank=True, help_text='A reason why the harvest failed that our system does not know.', max_length=255, null=True, verbose_name='Harvest Failure Reason (Other)'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Bad'), (3, 'Average'), (2, 'Good'), (1, 'Excellent')], help_text='The harvest quality rating when the crop production has finished.', null=True, verbose_name='Harvest quality'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_weight',
            field=models.FloatField(blank=True, help_text='The harvest weight at completion.', null=True, verbose_name='Harvest weight'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_weight_unit',
            field=models.CharField(blank=True, help_text='The harvest weight unit of measure at completion.', max_length=15, null=True, verbose_name='Harvest weight unit of measure'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_yield',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Bad'), (3, 'Average'), (2, 'Good'), (1, 'Excellent')], help_text='The harvest yield rating when the crop production has finished.', null=True, verbose_name='Harvest yield'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='was_alive_after_harvest',
            field=models.NullBooleanField(default=None, help_text='Indicates if this `crop` organism was considered alive when harvested or not.', verbose_name='Was alive after harvest?'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='was_harvested',
            field=models.NullBooleanField(default=None, help_text='Indicates if this crop production was harvested or not.', verbose_name='Was this crop production harvseted?'),
        ),
        migrations.AlterField(
            model_name='production',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes to add upon the completion or operation of the production.', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='productioncrop',
            name='harvest_notes',
            field=models.TextField(blank=True, help_text='Any notes or notes of the harvest when the crop production has finished or during operation.', null=True, verbose_name='Harvest notes'),
        ),
        migrations.AlterField(
            model_name='productioncrop',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes or notes of the crop when the production has finished.', null=True, verbose_name='Notes at finish'),
        ),
    ]
