# Generated by Django 2.1.7 on 2019-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190417_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='last_24h_median_value',
            field=models.FloatField(blank=True, editable=False, help_text='The latest measured median value within the last 24 hours of operation.', null=True, verbose_name='Last 24h median value'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_24h_stedv_value',
            field=models.FloatField(blank=True, editable=False, help_text='The standard deviation value of the past 24 hours.', null=True, verbose_name='last_24h_stedv_value'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_24h_variance_value',
            field=models.FloatField(blank=True, editable=False, help_text='The variance value of the past 24 hours.', null=True, verbose_name='last_24h_variance_value'),
        ),
    ]
