# Generated by Django 2.2.1 on 2019-07-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190702_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='subscription_monthly_fee',
        ),
        migrations.RemoveField(
            model_name='store',
            name='subscription_monthly_fee_currency',
        ),
        migrations.RemoveField(
            model_name='store',
            name='subscription_name',
        ),
    ]
