# Generated by Django 2.2.1 on 2019-05-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190508_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productioncrop',
            old_name='harvest_review_at_finish',
            new_name='harvest_at_finish',
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_failure_reason_at_finish',
            field=models.TextField(blank=True, help_text='Th harvest failure reason of the crop when the production has finished.', null=True, verbose_name='Harvest failure at finish'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='state_failure_reason_at_finish',
            field=models.TextField(blank=True, help_text='Th failure reason of the crop when the production has finished.', null=True, verbose_name='Failure reason at finish'),
        ),
    ]
