# Generated by Django 2.2.1 on 2019-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_productioncrop_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncropinspection',
            name='average_height',
            field=models.FloatField(blank=True, help_text='The average height of the production crop at inspection.', null=True, verbose_name='Average Height'),
        ),
        migrations.AddField(
            model_name='productioncropinspection',
            name='average_length',
            field=models.FloatField(blank=True, help_text='The average length of the production crop at inspection.', null=True, verbose_name='Average Length'),
        ),
        migrations.AddField(
            model_name='productioncropinspection',
            name='average_measure_unit',
            field=models.CharField(blank=True, help_text='A unit of measurement used for the averages measurements at inspection.', max_length=15, null=True, verbose_name='Average Measure Unit of measurement'),
        ),
        migrations.AddField(
            model_name='productioncropinspection',
            name='average_width',
            field=models.FloatField(blank=True, help_text='The average wdith of the production crop at inspection.', null=True, verbose_name='Average Width'),
        ),
    ]
