# Generated by Django 2.1.7 on 2019-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190318_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], help_text='The frequency with which a subscription should be billed.', max_length=31, verbose_name='Interval'),
        ),
    ]
