# Generated by Django 2.1.7 on 2019-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190420_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(default=1, help_text='The description of the invoice item.', max_length=127, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
