# Generated by Django 2.2.1 on 2019-07-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190709_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding_survey_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='was_onboarded',
        ),
    ]
