# Generated by Django 2.2.1 on 2019-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190703_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=1, help_text='The short description of this product.', max_length=63, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
