# Generated by Django 2.2.1 on 2019-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190709_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(help_text='The unique identifier used by us to identify a device in our system and we keep internal to our system (i.e. we do not release it to customer).', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.BigAutoField(help_text='The unique identifier used by us to identify an instrument in our system and we keep internal to our system (i.e. we do not release it to the customer).', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
