# Generated by Django 2.1.7 on 2019-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190325_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_measured_unit_of_measure',
            field=models.CharField(blank=True, editable=False, help_text='The last measured unit of measure since operation.', max_length=7, null=True, verbose_name='Last measured unit of measure'),
        ),
    ]
