# Generated by Django 2.2.1 on 2019-05-26 23:42

from django.db import migrations, models
import mikaponics.s3utils


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190526_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesimagedatum',
            name='image_value',
            field=models.ImageField(blank=True, help_text='The image file of the time-series datum.', null=True, storage=mikaponics.s3utils.PrivateMediaStorage(), upload_to='image-data/%Y/%m/%d/', verbose_name='Image Value'),
        ),
    ]
