# Generated by Django 2.2.1 on 2019-05-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20190519_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncropinspection',
            name='review',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Terrible')], help_text='The review of the user for this crop at this time.', null=True, verbose_name='Review'),
        ),
    ]
