# Generated by Django 2.2.1 on 2019-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190524_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_production_inspection_task_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='production_inspection_task_frequency',
        ),
        migrations.AddField(
            model_name='production',
            name='next_scheduled_inspection_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the next scheduled inspection.', null=True, verbose_name='Next scheduled inspection at'),
        ),
        migrations.AddField(
            model_name='production',
            name='scheduled_inspection_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Daily'), (3, 'Weekly'), (3, 'Bi-Weekly'), (4, 'Monthly')], default=3, help_text='The frequency to create `production inspection` tasks.', verbose_name='Scheduled Inspections frequency'),
        ),
    ]
