# Generated by Django 2.1.7 on 2019-03-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190318_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, editable=False, help_text='The subscription plan this user is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='foundation.SubscriptionPlan'),
        ),
    ]
