# Generated by Django 2.2.1 on 2019-05-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190503_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncrop',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Production Crop', 'verbose_name_plural': 'Production Crops'},
        ),
    ]
