# Generated by Django 2.2.1 on 2019-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190517_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Humidity'), (2, 'Temperature'), (3, 'Total Volatile Organic Compound'), (4, 'Carbon Dioxide'), (5, 'Air Pressure'), (6, 'Altitude'), (7, 'Water Level'), (8, 'Power Usage'), (9, 'pH'), (10, 'Electrical Conductivity'), (11, 'Oxidation-Reduction Potential'), (12, 'Camera'), (13, 'Heat Vision'), (14, 'UV Light'), (15, 'Triad Spectroscopy')], help_text='The type of instrument this is.', verbose_name='type of'),
        ),
    ]
