# Generated by Django 2.1.7 on 2019-03-29 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190325_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time that the customer received their order for this invoice.', verbose_name='Delivered at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time that the customer purchased this invoice.', verbose_name='Purchased at'),
            preserve_default=False,
        ),
    ]
