# Generated by Django 2.2.1 on 2019-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190707_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='The unique slug used for this crop when accessing details page.', max_length=127, unique=True, verbose_name='Slug')),
                ('text', models.CharField(blank=True, db_index=True, help_text='The variety name of the crop.', max_length=127, null=True, verbose_name='Text')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'Pest'), (2, 'Disease'), (3, 'Abiotic')], help_text='The type of production crop problem.', verbose_name='Type of')),
            ],
            options={
                'verbose_name': 'Problem Data Sheet',
                'verbose_name_plural': 'Problem Data Sheets',
                'db_table': 'mika_problem_data_sheet',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
