# Generated by Django 2.2.1 on 2019-05-15 01:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190514_0240'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_device_created_b79d00_brin'),
        ),
        migrations.AddIndex(
            model_name='devicereport',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_device_created_f1f031_brin'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_instru_created_94be06_brin'),
        ),
        migrations.AddIndex(
            model_name='instrumentanalysis',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_instru_created_2a4473_brin'),
        ),
        migrations.AddIndex(
            model_name='instrumentsimulator',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_instru_created_b02f78_brin'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_produc_created_7b1ad0_brin'),
        ),
        migrations.AddIndex(
            model_name='productioncrop',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_produc_created_1b6f2b_brin'),
        ),
        migrations.AddIndex(
            model_name='productioncropinspection',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_produc_created_108db7_brin'),
        ),
        migrations.AddIndex(
            model_name='productioninspection',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at', 'last_modified_at'], name='mika_produc_created_1327fd_brin'),
        ),
    ]
