# Generated by Django 2.2.1 on 2019-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190520_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncrop',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, help_text='The datetime of the when the evaluation was done.', null=True, verbose_name='Evaluated At'),
        ),
    ]
