# Generated by Django 2.2.1 on 2019-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20190702_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='The date when the subscription started / will start.', null=True, verbose_name='Subscription Start Date'),
        ),
    ]
