# Generated by Django 2.2.1 on 2019-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190525_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='next_scheduled_inspection_at',
        ),
        migrations.RemoveField(
            model_name='production',
            name='scheduled_inspection_frequency',
        ),
        migrations.AddField(
            model_name='production',
            name='inspection_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Daily'), (3, 'Weekly'), (3, 'Bi-Weekly'), (4, 'Monthly')], default=3, help_text='The frequency to create `production inspection` tasks.', verbose_name='Inspections frequency'),
        ),
        migrations.AddField(
            model_name='production',
            name='next_inspection_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the next scheduled inspection.', null=True, verbose_name='Next inspection at'),
        ),
    ]
