# Generated by Django 2.2.1 on 2019-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190511_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='was_success_at_finish',
            field=models.NullBooleanField(default=None, help_text='Indicates if this crop production was considered a success to the user or a failure.', verbose_name='Was this crop production a success upon completion?'),
        ),
    ]
