# Generated by Django 2.1.7 on 2019-03-18 12:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The subscription details from the payment merchant.', null=True, verbose_name='Subscription Data'),
        ),
    ]
