# Generated by Django 2.2.1 on 2019-05-20 22:08

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_productioncrop_evaluated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, help_text='The datetime of the when the evaluation was done.', null=True, verbose_name='Evaluated At'),
        ),
        migrations.AddField(
            model_name='production',
            name='evaluation_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The evaluation details for this particular score in the present date and time.', max_length=511, null=True, verbose_name='Evaluation Dictionary'),
        ),
        migrations.AddField(
            model_name='production',
            name='evaluation_score',
            field=models.FloatField(blank=True, help_text='The evaluation score of the current production in the current present date and time.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='Evaluation'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_evaluation_score_indeterminate',
            field=models.BooleanField(blank=True, default=False, help_text='Value determines if the production score can be computed or not. If this is `true`, the reason is because the user is growing a `other` crop which our system does not have a record of.', verbose_name='Is evaluation score indeterminate?'),
        ),
    ]
