# Generated by Django 2.2.1 on 2019-05-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190517_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_consumption_in_kilowatts_per_hour',
            field=models.FloatField(blank=True, help_text='The amount of energy consumed by this device, and all the attached instruments, per kilowatt hours.', null=True, verbose_name='Power consumption in kilowatts per hour'),
        ),
    ]
