# Generated by Django 2.2.1 on 2019-07-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190703_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='configuration',
        ),
    ]
