# Generated by Django 2.2.1 on 2019-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_user_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='The subscription ID assigned to the customer from the payment merchant for the subscription.', max_length=127, null=True, verbose_name='Subscription ID'),
        ),
    ]
