# Generated by Django 2.1.7 on 2019-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190329_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, help_text='The unique slug used for this invoice when accessing invoice details page.', max_length=63, unique=True, verbose_name='Slug'),
        ),
    ]
