# Generated by Django 2.2.1 on 2019-05-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190503_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInspection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='The unique slug used for this food production inspection when accessing details page.', max_length=127, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address of the creator.', null=True, verbose_name='Created from IP')),
                ('created_from_is_public', models.BooleanField(blank=True, default=False, editable=False, help_text='Is creator a public IP and is routable.', verbose_name='Is created from IP public?')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from IP')),
                ('last_modified_from_is_public', models.BooleanField(blank=True, default=False, editable=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is Last modified from IP public?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user whom created this food production inspections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_inspections', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The user whom last modified this food production inspection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_production_inspections', to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(blank=True, help_text='The food production operation this quality assurance inspection is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='foundation.Production')),
                ('production_crop', models.ForeignKey(blank=True, help_text='The plants or fish that we are evaluating for this quality assurance inspection.', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='foundation.ProductionCrop', verbose_name='Production Crop')),
            ],
            options={
                'verbose_name': 'Production Inspection',
                'verbose_name_plural': 'Production Inspections',
                'db_table': 'mika_production_inspections',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
