# Generated by Django 2.2.1 on 2019-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_auto_20190522_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='alert_below_value',
        ),
        migrations.RemoveField(
            model_name='production',
            name='alert_delay_in_seconds',
        ),
        migrations.AddField(
            model_name='production',
            name='orange_alert_delay_in_seconds',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Every minute'), (120, 'Every 2 minutes'), (300, 'Every 5 minutes'), (600, 'Every 10 minutes'), (1200, 'Every 20 minutes'), (1800, 'Every 30 minutes'), (3600, 'Every hour'), (7200, 'Every 2 hours'), (14400, 'Every 4 hours'), (21600, 'Every 6 hours'), (43200, 'Every 12 hours'), (86400, 'Every 24 hours')], default=60, help_text='The time that orange alerts will be sent from the last time the orange alert was sent.', verbose_name='Orange alert delay (seconds)'),
        ),
        migrations.AddField(
            model_name='production',
            name='orange_below_value',
            field=models.FloatField(blank=True, help_text='The value that if is less then or equal to then our system will trigger a orange alert.', null=True, verbose_name='Orange below value'),
        ),
        migrations.AddField(
            model_name='production',
            name='red_alert_delay_in_seconds',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Every minute'), (120, 'Every 2 minutes'), (300, 'Every 5 minutes'), (600, 'Every 10 minutes'), (1200, 'Every 20 minutes'), (1800, 'Every 30 minutes'), (3600, 'Every hour'), (7200, 'Every 2 hours'), (14400, 'Every 4 hours'), (21600, 'Every 6 hours'), (43200, 'Every 12 hours'), (86400, 'Every 24 hours')], default=60, help_text='The time that red alerts will be sent from the last time the red alert was sent.', verbose_name='Red alert delay (seconds)'),
        ),
        migrations.AddField(
            model_name='production',
            name='red_below_value',
            field=models.FloatField(blank=True, help_text='The value that if is less then or equal to then our system will trigger a red alert.', null=True, verbose_name='Red below value'),
        ),
        migrations.AddField(
            model_name='production',
            name='yellow_alert_delay_in_seconds',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Every minute'), (120, 'Every 2 minutes'), (300, 'Every 5 minutes'), (600, 'Every 10 minutes'), (1200, 'Every 20 minutes'), (1800, 'Every 30 minutes'), (3600, 'Every hour'), (7200, 'Every 2 hours'), (14400, 'Every 4 hours'), (21600, 'Every 6 hours'), (43200, 'Every 12 hours'), (86400, 'Every 24 hours')], default=60, help_text='The time that yellow alerts will be sent from the last time the yellow alert was sent.', verbose_name='Yellow alert delay (seconds)'),
        ),
        migrations.AddField(
            model_name='production',
            name='yellow_below_value',
            field=models.FloatField(blank=True, help_text='The value that if is less then or equal to then our system will trigger a yellow alert.', null=True, verbose_name='Yellow below value'),
        ),
    ]
