# Generated by Django 2.1.7 on 2019-03-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_invoice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentanalysis',
            name='slug',
            field=models.SlugField(blank=True, help_text='The unique slug used for this instrument analysis when accessing details page.', max_length=127, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(blank=True, help_text='The unique slug used for this device when accessing device details page.', max_length=127, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(blank=True, help_text='The unique slug used for this instrument when accessing details page.', max_length=127, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, help_text='The unique slug used for this invoice when accessing details page.', max_length=127, unique=True, verbose_name='Slug'),
        ),
    ]
