# Generated by Django 2.2.1 on 2019-05-17 23:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_device_power_consumption_in_kilowatts_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesdatum',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The values for this datum.', null=True, verbose_name='Values'),
        ),
    ]
