# Generated by Django 2.2.1 on 2019-05-03 21:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_productioninspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='stages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Stages of development this crop has in their lifespan.', verbose_name='Life Cycle Stages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='environment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Indoor'), (2, 'Outdoor')], default=1, help_text='The type of environment the production is taking place in.', verbose_name='Environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='finish',
            field=models.DateTimeField(blank=True, help_text='The date/time this production finished.', null=True, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='production',
            name='start',
            field=models.DateTimeField(blank=True, help_text='The date/time this production started.', null=True, verbose_name='Start'),
        ),
        migrations.AddField(
            model_name='production',
            name='system',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wick System'), (2, 'Deep Water Culture System'), (3, 'Ebb & Flow System'), (4, 'Nutrient Film Technique System'), (5, 'Drip System'), (6, 'Aeroponic System'), (7, 'Vertical Tower System'), (8, 'Other (Please specify)')], default=1, help_text='The system being used for production.', verbose_name='System'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aquaponics'), (2, 'Hydroponics'), (3, 'Aquaculture')], default=1, help_text='The type of production.', verbose_name='Type of'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productioninspection',
            name='review',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (4, 'Bad'), (3, 'Average'), (2, 'Good'), (1, 'Excellent')], default=1, help_text='The review of the user for this crop at this time.', verbose_name='Review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productioninspection',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1, help_text='The observed stage in the life cycle by the user.', verbose_name='Life Cycle Stage'),
            preserve_default=False,
        ),
    ]
