# Generated by Django 2.2.1 on 2019-07-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_auto_20190707_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncropinspection',
            name='abiotic_problems',
        ),
        migrations.RemoveField(
            model_name='productioncropinspection',
            name='disease_problems',
        ),
        migrations.RemoveField(
            model_name='productioncropinspection',
            name='pest_problems',
        ),
        migrations.AddField(
            model_name='productioncropinspection',
            name='problems',
            field=models.ManyToManyField(blank=True, help_text='The problems found for this particular inspection.', related_name='production_crop_inspections', to='foundation.ProblemDataSheet'),
        ),
    ]
