# Generated by Django 2.2.1 on 2019-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_auto_20190525_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='inspection_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Daily'), (3, 'Weekly'), (4, 'Bi-Weekly'), (5, 'Monthly')], default=3, help_text='The frequency to create `production inspection` tasks.', verbose_name='Inspections frequency'),
        ),
    ]
