# Generated by Django 2.2.1 on 2019-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_auto_20190522_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_production_inspection_task_created_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the last production inspection task was created.', null=True, verbose_name='Last production inspection task created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_report_email_created_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the last report email was created.', null=True, verbose_name='Last report email created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='production_inspection_task_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Daily'), (3, 'Weekly'), (3, 'Bi-Weekly'), (4, 'Monthly')], default=3, help_text='The frequency to create `production inspection` tasks.', verbose_name='Production Inspection Task frequency'),
        ),
    ]
