# Generated by Django 2.2.1 on 2019-05-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_timeseriesdatum_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Online'), (3, 'Offline'), (4, 'Error')], default=1, help_text='The state of device.', verbose_name='State'),
        ),
    ]
