# Generated by Django 2.2.1 on 2019-05-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_auto_20190503_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='production',
            name='start',
        ),
        migrations.AddField(
            model_name='production',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='The date/time this production finished.', null=True, verbose_name='Finished at'),
        ),
        migrations.AddField(
            model_name='production',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='The date/time this production started.', null=True, verbose_name='Started at'),
        ),
    ]
