# Generated by Django 2.2.1 on 2019-05-12 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_auto_20190512_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninspection',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Submitted')], default=1, help_text='The state of inspection.', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='productioninspection',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user whom created this crop production inspections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productioninspection',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user whom last modified this crop production inspection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_production_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productioninspection',
            name='production',
            field=models.ForeignKey(blank=True, help_text='The crop production operation this quality assurance inspection is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='foundation.Production'),
        ),
        migrations.AlterField(
            model_name='productioninspection',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='The unique slug used for this crop production inspection when accessing details page.', max_length=127, unique=True, verbose_name='Slug'),
        ),
    ]
