# Generated by Django 2.2.1 on 2019-05-20 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_croplifesupportcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplifesupportcondition',
            name='max_air_temperature',
        ),
        migrations.RemoveField(
            model_name='croplifesupportcondition',
            name='min_air_temperature',
        ),
        migrations.AddField(
            model_name='croplifesupportcondition',
            name='max_day_air_temperature',
            field=models.FloatField(default=1, help_text='The maximum acceptable air temperature value this crop can accept for this life-cycle stage in the day. Measured in celsius.', validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Day Air Temperature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='croplifesupportcondition',
            name='max_night_air_temperature',
            field=models.FloatField(default=1, help_text='The maximum acceptable air temperature value this crop can accept for this life-cycle stage at night. Measured in celsius.', validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Night Air Temperature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='croplifesupportcondition',
            name='min_day_air_temperature',
            field=models.FloatField(default=1, help_text='The minimum acceptable air temperature value this crop can accept for this life-cycle stage in the day. Measured in celsius.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Day Air Temperature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='croplifesupportcondition',
            name='min_night_air_temperature',
            field=models.FloatField(default=1, help_text='The minimum acceptable air temperature value this crop can accept for this life-cycle stage at night. Measured in celsius.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Night Air Temperature'),
            preserve_default=False,
        ),
    ]
