# Generated by Django 2.2.1 on 2019-05-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_auto_20190503_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncrop',
            name='comments_at_finish',
            field=models.TextField(blank=True, help_text='Any comments or notes of the crop when the production has finished.', null=True, verbose_name='Comments at finish'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_comments_at_finish',
            field=models.TextField(blank=True, help_text='Any comments or notes of the harvest when the production has finished.', null=True, verbose_name='Harvest comments at finish'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_review_at_finish',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Bad'), (3, 'Average'), (2, 'Good'), (1, 'Excellent')], help_text='The harvest review made by the user when the production has finished.', null=True, verbose_name='Harvest review at finish'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='state_at_finish',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Crops died'), (2, 'Crops were alive'), (3, 'Crops were alive at harvest'), (4, 'Crops were terminated'), (5, 'Crops were terminated with harvest')], help_text='The state of the crop when the production has finished.', null=True, verbose_name='State at finish'),
        ),
    ]
