# Generated by Django 2.2.1 on 2019-05-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_auto_20190520_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdatasheet',
            name='life_dict',
        ),
    ]
