# Generated by Django 2.2.1 on 2019-05-23 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_auto_20190523_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='device',
            field=models.ForeignKey(blank=True, help_text='The device this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='foundation.Device'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The instrument this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='foundation.Instrument'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='production',
            field=models.ForeignKey(blank=True, help_text='The production this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='foundation.Production'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='production_crop',
            field=models.ForeignKey(blank=True, help_text='The production crop this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='foundation.ProductionCrop'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='device',
            field=models.ForeignKey(blank=True, help_text='The device this alert belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_items', to='foundation.Device'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The instrument this alert belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_items', to='foundation.Instrument'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='production',
            field=models.ForeignKey(blank=True, help_text='The production this alert belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_items', to='foundation.Production'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='production_crop',
            field=models.ForeignKey(blank=True, help_text='The production crop this alert belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_items', to='foundation.ProductionCrop'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='user',
            field=models.ForeignKey(help_text='The user this alert belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='alert_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
