# Generated by Django 2.2.1 on 2019-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_auto_20190525_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='inspections_started_at',
            field=models.DateTimeField(blank=True, help_text="The date/time this production's inspections will start.", null=True, verbose_name='Inspections Started at'),
        ),
    ]
