# Generated by Django 2.2.1 on 2019-05-18 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_auto_20190518_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncrop',
            name='evaluation_score',
            field=models.FloatField(blank=True, help_text='The evaluation score of the current crop in the current present date and time.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='Evaluation'),
        ),
    ]
