# Generated by Django 2.2.1 on 2019-05-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_auto_20190503_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncrop',
            name='comments_at_finish',
        ),
        migrations.RemoveField(
            model_name='productioncrop',
            name='harvest_comments_at_finish',
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='harvest_notes_at_finish',
            field=models.TextField(blank=True, help_text='Any notes or notes of the harvest when the production has finished.', null=True, verbose_name='Harvest notes at finish'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='notes_at_finish',
            field=models.TextField(blank=True, help_text='Any notes or notes of the crop when the production has finished.', null=True, verbose_name='Comments at finish'),
        ),
        migrations.AddField(
            model_name='productioninspection',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes for this inspection.', null=True, verbose_name='Notes'),
        ),
    ]
