# Generated by Django 2.2.1 on 2019-05-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_auto_20190518_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropsubstrate',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Crop Substrate', 'verbose_name_plural': 'Crop Substrates'},
        ),
    ]
