# Generated by Django 2.2.1 on 2019-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_auto_20190520_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropcondition',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Humidity'), (2, 'Day Air Temperature'), (3, 'Night Air Temperature'), (4, 'Water Temperature'), (5, 'Total Volatile Organic Compound'), (6, 'Carbon Dioxide'), (7, 'Air Pressure'), (8, 'Altitude'), (9, 'pH'), (10, 'Electrical Conductivity'), (11, 'Oxidation-Reduction Potential'), (12, 'UV Light')], help_text='The type of instrument this is condition belongs to.', verbose_name='type of'),
        ),
    ]
