# Generated by Django 2.2.1 on 2019-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_auto_20190503_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='system_other',
            field=models.CharField(blank=True, help_text='The description of the other system.', max_length=63, null=True, verbose_name='System (Other)'),
        ),
    ]
