# Generated by Django 2.2.1 on 2019-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_auto_20190521_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='is_evaluation_score_indeterminate',
        ),
        migrations.RemoveField(
            model_name='productioncrop',
            name='is_evaluation_score_indeterminate',
        ),
        migrations.AddField(
            model_name='production',
            name='evaluation_error',
            field=models.CharField(blank=True, help_text='The evaluation error message explaining why the evaluation could not be computed.', max_length=255, null=True, verbose_name='Evaluation Error'),
        ),
        migrations.AddField(
            model_name='productioncrop',
            name='evaluation_error',
            field=models.CharField(blank=True, help_text='The evaluation error message explaining why the evaluation could not be computed.', max_length=255, null=True, verbose_name='Evaluation Error'),
        ),
        migrations.AlterField(
            model_name='cropcondition',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Humidity'), (2, 'Day Air Temperature'), (3, 'Night Air Temperature'), (4, 'Water Temperature'), (5, 'Total Volatile Organic Compound'), (6, 'Carbon Dioxide'), (7, 'Air Pressure'), (8, 'Altitude'), (9, 'pH'), (10, 'Electrical Conductivity'), (11, 'Oxidation-Reduction Potential'), (13, 'UV Light')], help_text='The type of instrument this is condition belongs to.', verbose_name='type of'),
        ),
    ]
