# Generated by Django 2.2.1 on 2019-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_production_system_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='is_commercial',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if this production running for commercial purposes.', verbose_name='Commercial purposes?'),
        ),
    ]
