# Generated by Django 2.2.1 on 2019-05-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_auto_20190521_0115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cropcondition',
            unique_together=set(),
        ),
    ]
