# Generated by Django 2.2.1 on 2019-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_productioncrop_is_evaluation_score_indeterminate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncrop',
            name='is_evaluation_score_indeterminate',
            field=models.BooleanField(blank=True, default=False, help_text='Value determines if the crop score can be computed or not. If this is `true`, the reason is because the user is growing a `other` crop which our system does not have a record of.', verbose_name='Is evaluation score indeterminate?'),
        ),
    ]
