# Generated by Django 2.2.1 on 2019-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_production_is_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='is_commercial',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if this production running for commercial purposes or not.', verbose_name='Is for commercial purposes?'),
        ),
    ]
