# Generated by Django 2.2.1 on 2019-05-21 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_auto_20190521_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='evaluation_dict',
        ),
        migrations.RemoveField(
            model_name='production',
            name='evaluation_error',
        ),
        migrations.AlterField(
            model_name='productioncrop',
            name='evaluation_score',
            field=models.FloatField(blank=True, help_text='The evaluation score of the current crop in the current present date and time.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='Evaluation Score'),
        ),
    ]
