# Generated by Django 2.2.1 on 2019-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_auto_20190504_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='description',
            field=models.TextField(default='', help_text='A description of the crop production.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='production',
            name='name',
            field=models.CharField(default='test', help_text='The name of the crop production.', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
